{% set rev = "release_2018.4" %}
{% set name = "sfepy" %}
{% set org = "sfepy" %}
{% set version = "2018.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/{{ org }}/{{ name }}.git
  git_rev: {{ rev }}

build:
  number: 0

requirements:
  build:
    - python {{PY_VER}}*,>=2.7,<3.7
    - cython
    - numpy>=1.11.*
    - scipy
    - pyparsing
    - pytables>=3.3.*
    - matplotlib

  run:
    - python {{PY_VER}}*,>=2.7,<3.7
    - {{ pin_compatible('numpy') }}
    - scipy
    - pyparsing
    - pytables
    - matplotlib
    - sympy

test:
  imports:
    - sfepy
  source_files:
    - run_tests.py
    - tests/
    - examples/
  commands:
    - python run_tests.py

about:
  home: http://{{ name }}.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "Simple finite elements in Python"
  description: >-
    SfePy is a software for solving systems of coupled partial
    differential equations (PDEs) by the finite element method in 1D,
    2D and 3D. It can be viewed both as black-box PDE solver, and as a
    Python package which can be used for building custom
    applications. The word simple means that complex FEM problems can
    be coded very easily and rapidly.
  doc_url: http://sfepy.org
  dev_url: https://github.com/sfepy/sfepy

extra:
  recipe-maintainers:
    - rc
    - wd15
