{% set version = "2025.2" %}

package:
  name: sfepy
  version: {{ version }}

source:
  url: https://github.com/sfepy/sfepy/archive/release_{{ version }}.zip
  sha256: 61c8c7fe3b3438402e30e32b4e365737c2bc2eb0c8e5794429cb761fe5abfa38

build:
  number: 0
  skip: true  # [win and py<311]
  entry_points:
    - sfepy-convert = sfepy.scripts.convert_mesh:main
    - sfepy-mesh = sfepy.scripts.gen_mesh:main
    - sfepy-probe = sfepy.scripts.probe:main
    - sfepy-run = sfepy.scripts.simple:main
    - sfepy-test = sfepy.scripts.run_tests:main
    - sfepy-view = sfepy.scripts.resview:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - python
    - scikit-build >=0.16.7
    - setuptools >=46.4
    - pip
    - cython
    - numpy
    - scipy
    - pytables
    - matplotlib-base
    - importlib-metadata
    - meshio
  run:
    - numpy
    - python
    - scipy
    - pyparsing
    - pytables
    - matplotlib-base
    - importlib-metadata
    - meshio
    - sympy
    - psutil

test:
  requires:
    - pytest
  source_files:
    - meshes/
  commands:
    # Workaround failing tests of scipy eigenvalue solvers on windows.
    {% set opts = "'-k not test_eigenvalue_solvers'" if win else "" %}
    - python -c "import sfepy, sys; sys.exit(sfepy.test({{ opts }}))"

about:
  home: http://sfepy.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "Simple finite elements in Python"
  description: >-
    SfePy is a software for solving systems of coupled partial differential equations (PDEs) by the finite element method in 1D, 2D and 3D. It can be viewed both as black-box PDE solver, and as a Python package which can be used for building custom applications. The word simple means that complex FEM problems can be coded
    very easily and rapidly.
  doc_url: http://sfepy.org
  dev_url: https://github.com/sfepy/sfepy

extra:
  recipe-maintainers:
    - rc
    - wd15
