{% set version = "2024.1" %}

package:
  name: sfepy
  version: {{ version }}

source:
  url: https://github.com/sfepy/sfepy/archive/release_{{ version }}.zip
  sha256: f9bbf7e8a0134ea58712bed06e2cd2bc260b633a37f99080e5eec14834043973

build:
  number: 0
  entry_points:
    - sfepy-convert = sfepy.scripts.convert_mesh:main
    - sfepy-mesh = sfepy.scripts.gen_mesh:main
    - sfepy-probe = sfepy.scripts.probe:main
    - sfepy-run = sfepy.scripts.simple:main
    - sfepy-test = sfepy.scripts.run_tests:main
    - sfepy-view = sfepy.scripts.resview:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - ninja
  host:
    - python
    - scikit-build >=0.16.7
    - setuptools >=46.4
    - pip
    - cython <3.0
    - numpy >=1.17
    - scipy
    - pytables
    - matplotlib-base
    - importlib_metadata
    - meshio 4.4.6
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pyparsing
    - pytables
    - matplotlib-base
    - importlib_metadata
    - meshio 4.4.6
    - sympy
    - psutil

test:
  requires:
    - pytest
  source_files:
    - meshes/
  commands:
    - python -c "import sfepy, sys; sys.exit(sfepy.test())"

about:
  home: http://sfepy.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "Simple finite elements in Python"
  description: >-
    SfePy is a software for solving systems of coupled partial differential equations (PDEs) by the finite element method in 1D, 2D and 3D. It can be viewed both as black-box PDE solver, and as a Python package which can be used for building custom applications. The word simple means that complex FEM problems can be coded
    very easily and rapidly.
  doc_url: http://sfepy.org
  dev_url: https://github.com/sfepy/sfepy

extra:
  recipe-maintainers:
    - rc
    - wd15
