{% set rev = "release_2019.1.1" %}
{% set name = "sfepy" %}
{% set org = "sfepy" %}
{% set version = "2019.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/{{ org }}/{{ name }}.git
  git_rev: {{ rev }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt"

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - python
    - cython
    - numpy
    - scipy
    - pyparsing
    - pytables
    - matplotlib

  run:
    - numpy
    - scipy
    - pyparsing
    - pytables
    - matplotlib
    - sympy

test:
  source_files:
    - run_tests.py
    - tests/
    - examples/
    - meshes/

  commands:
    - "{{ PYTHON }} run_tests.py"

about:
  home: http://{{ name }}.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "Simple finite elements in Python"
  description: >-
    SfePy is a software for solving systems of coupled partial
    differential equations (PDEs) by the finite element method in 1D,
    2D and 3D. It can be viewed both as black-box PDE solver, and as a
    Python package which can be used for building custom
    applications. The word simple means that complex FEM problems can
    be coded very easily and rapidly.
  doc_url: http://sfepy.org
  dev_url: https://github.com/sfepy/sfepy

extra:
  recipe-maintainers:
    - rc
    - wd15
